mode: rule
log-level: warning
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
find-process-mode: off
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true
external-controller: 0.0.0.0:9090
sniffer:
  enable: true
  sniff:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
    TLS:
      ports:
        - 443
        - 8443
    QUIC:
      ports:
        - 443
        - 8443
  force-domain:
    - +.v2ex.com
  skip-domain:
    - +.baidu.com
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - rule-set:private_domain,cn_domain
    - +.msftconnecttest.com
    - +.msftncsi.com
    - time.*.com
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 8.8.8.8
    - 1.1.1.1
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png
  - name: Final
    type: select
    proxies:
      - DIRECT
      - Proxy
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Final.png
  - name: YouTube
    type: select
    proxies:
      - DIRECT
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png
  - name: Google
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Google.png
  - name: ChatGPT
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/ChatGPT.png
  - name: GitHub
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/GitHub.png
  - name: Microsoft
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Microsoft.png
  - name: TikTok
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/TikTok.png
  - name: Telegram
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Telegram.png
  - name: NETFLIX
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Netflix.png
  - name: PayPal
    type: select
    proxies:
      - Proxy
      - 自动选择
      - 香港节点
      - 日本节点
      - 美国节点
      - 全部节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/PayPal.png
  - name: Apple
    type: select
    proxies:
      - Proxy
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Apple.png
  - name: 香港节点
    type: select
    include-all: true
    filter: (?i)港|hk|hongkong|hong kong
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/CN.png
  - name: 日本节点
    type: select
    include-all: true
    filter: (?i)日|jp|japan
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/JP.png
  - name: 美国节点
    type: select
    include-all: true
    filter: (?i)美|us|unitedstates|united states
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/US.png
  - name: 自动选择
    type: url-test
    include-all: true
    tolerance: 20
    interval: 300
    filter: ^((?!(直连)).)*$
    lazy: true
  - name: 全部节点
    type: select
    include-all: true
    icon: https://github.com/shindgewongxj/WHATSINStash/raw/main/icon/select.png
rules:
  - RULE-SET,apple_domain,Apple
  - RULE-SET,ai,ChatGPT
  - RULE-SET,github_domain,GitHub
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,onedrive_domain,OneDrive
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,speedtest_domain,Speedtest
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,paypal_domain,PayPal
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,netflix_ip,NETFLIX,no-resolve
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,proxylite,Proxy
  - RULE-SET,geolocation-!cn,Proxy
  - RULE-SET,gfw_domain,Proxy
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,cn_ip,DIRECT
  - MATCH,Final
rule-anchor:
  ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
  domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
  class:
    type: http
    interval: 86400
    behavior: classical
    format: text
rule-providers:
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml
  proxylite:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list
  ai:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.yaml
  youtube_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml
  google_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml
  github_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml
  telegram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml
  netflix_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml
  paypal_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.yaml
  onedrive_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.yaml
  microsoft_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml
  apple_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.yaml
  speedtest_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.yaml
  tiktok_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.yaml
  gfw_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.yaml
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml
  google_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml
  telegram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml
  netflix_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.yaml
